#cloud-config
ssh_pwauth: True
chpasswd:
  list: |
    root:r3dH@t26
  expire: False

# groups:
#   - ansible

# Add users to the system. Users are added after groups are added.
# users:
#   - default
#   - name:  ansible
#     gecos: ansible
#     shell: /bin/bash
#     primary_group: ansible
#     sudo: ALL=(ALL) NOPASSWD:ALL
#     groups: users, admin, wheel
#     lock_passwd: false
#     ssh_authorized_keys:
#       - ${key_file}

# packages:
#   - emacs

# runcmd:
#   - echo 1
